/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package awt_ex;

import java.awt.Dialog;

/**
 *
 * @author manasvi
 */
public class MainFrame extends java.awt.Frame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button2 = new java.awt.Button();
        button3 = new java.awt.Button();
        button4 = new java.awt.Button();
        button5 = new java.awt.Button();
        panel1 = new java.awt.Panel();
        button1 = new java.awt.Button();
        button7 = new java.awt.Button();
        button8 = new java.awt.Button();
        button9 = new java.awt.Button();
        panel2 = new java.awt.Panel();
        button10 = new java.awt.Button();
        button11 = new java.awt.Button();
        button12 = new java.awt.Button();
        button13 = new java.awt.Button();
        panel3 = new java.awt.Panel();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });

        button2.setLabel("button2");
        add(button2, java.awt.BorderLayout.NORTH);

        button3.setLabel("button3");
        add(button3, java.awt.BorderLayout.SOUTH);

        button4.setLabel("button4");
        add(button4, java.awt.BorderLayout.EAST);

        button5.setLabel("button5");
        add(button5, java.awt.BorderLayout.WEST);

        panel1.setLayout(new java.awt.BorderLayout());

        button1.setLabel("button1");
        panel1.add(button1, java.awt.BorderLayout.EAST);

        button7.setLabel("button7");
        panel1.add(button7, java.awt.BorderLayout.NORTH);

        button8.setLabel("button8");
        panel1.add(button8, java.awt.BorderLayout.SOUTH);

        button9.setLabel("button9");
        panel1.add(button9, java.awt.BorderLayout.WEST);

        panel2.setLayout(new java.awt.BorderLayout());

        button10.setLabel("button10");
        panel2.add(button10, java.awt.BorderLayout.NORTH);

        button11.setLabel("button11");
        panel2.add(button11, java.awt.BorderLayout.SOUTH);

        button12.setLabel("button12");
        panel2.add(button12, java.awt.BorderLayout.EAST);

        button13.setLabel("button13");
        button13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button13ActionPerformed(evt);
            }
        });
        panel2.add(button13, java.awt.BorderLayout.WEST);
        panel2.add(panel3, java.awt.BorderLayout.CENTER);

        panel1.add(panel2, java.awt.BorderLayout.CENTER);

        add(panel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Exit the Application
     */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button13ActionPerformed
        // TODO add your handling code here:
        
        Dialog d= new Dialog(this,"WOW");
        d.setSize(200, 200);
        d.setVisible(true);
        
    }//GEN-LAST:event_button13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button10;
    private java.awt.Button button11;
    private java.awt.Button button12;
    private java.awt.Button button13;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Button button7;
    private java.awt.Button button8;
    private java.awt.Button button9;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    // End of variables declaration//GEN-END:variables
}
